# Generated by Django 3.2.16 on 2022-11-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221104_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['recipe'], 'verbose_name': 'Список товара', 'verbose_name_plural': 'Списки товаров'},
        ),
    ]
