# Generated by Django 3.2.16 on 2022-11-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20221105_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredinets', through='recipes.IngredientInRecipe', to='recipes.Ingredient', verbose_name='Ингредиенты рецепта'),
        ),
    ]
