# Generated by Django 4.1.2 on 2022-10-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Введите электронную почту пользователя",
                max_length=254,
                unique=True,
                verbose_name="Электронная почта пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя пользователя",
                max_length=150,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                help_text="Введите фамилию пользователя",
                max_length=150,
                verbose_name="Фамилия пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="Введите уникальное имя пользователя",
                max_length=150,
                unique=True,
                verbose_name="Уникальное имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор на которого подписан",
            ),
        ),
    ]
